services:
  - type: web
    name: pkp-web
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__Provider
        value: postgresql
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: ObjectStorage__Enabled
        value: "false"
      - key: SeedSuperAdmin__Email
        sync: false
      - key: SeedSuperAdmin__Password
        sync: false
